version: '3.3'

services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend.local


  service:
    env_file:
      - .env
    build: .
    volumes:
      - static_files_volume:/app/static
    networks:
      - my-network


  # Добавила инит контейнер, который запускает миграции после страрта БД.
  # Так как не удалось запустить файл run_uwsgi.sh, не хватает прав.
  # ERROR: for service  Cannot start service service: OCI runtime create failed: runc create failed:
  # unable to start container process: exec: "./run_uwsgi.sh": permission denied: unknown
  # Пробовала в докерфайле создать группу, юзера, добавить юзера в эту группу и выдать права группе и юзеру на WORKDIR,
  # но это тоже не помогло, снова была ошибка с правами.

  init:
    env_file:
      - .env
    build: .
    entrypoint: sh -c "python manage.py migrate"
    networks:
      - my-network
    depends_on:
      - postgres


  nginx:
    image: nginx:1.25.3
    volumes:
      - static_files_volume:/app/static
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/site.conf:/etc/nginx/site.conf:ro
    depends_on:
      - service
    networks:
      - my-network


  swagger:
    image: swaggerapi/swagger-ui:latest
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/swagger/openapi.yaml:ro
    networks:
      - my-network

volumes:
  postgres-data:
  static_files_volume:

networks:
  backend.local:
    external: true
  my-network:
    external: true
